#!/usr/bin/env node
// Builds the add-on's icon set from Material Symbols (Rounded, weight 400):
//
//   thunderbird-addon/shared/icons.js   name → path data, for the add-on's pages
//   thunderbird-addon/icons/<name>.svg  standalone files, for chrome CSS masks and
//                                       the spaces toolbar (fill: context-fill)
//
// Only the names listed here are bundled. Custom glyphs (no Material match) live
// in CUSTOM below and follow the same 960-unit grid.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(root, "node_modules/@material-symbols/svg-400/rounded");

export const NAMES = [
  // shell and docks
  "chat", "forum", "left_panel_close", "left_panel_open", "right_panel_close", "right_panel_open", "open_in_full", "close_fullscreen",
  "remove", "close", "more_vert", "more_horiz", "settings", "search", "refresh", "add", "arrow_back", "arrow_forward", "arrow_upward",
  "chevron_right", "keyboard_arrow_up", "chevron_left", "keyboard_arrow_down", "check", "check_circle", "error", "warning", "info", "help",
  "send", "attach_file", "content_copy", "download", "upload", "open_in_new", "link", "delete", "edit", "drive_file_rename",
  "visibility", "visibility_off", "filter_list", "sort", "tune", "home", "folder", "folder_open", "create_new_folder", "description",
  "draft", "code", "terminal", "image", "movie", "music_note", "picture_as_pdf", "table", "slideshow", "article", "text_snippet",
  "play_arrow", "pause", "volume_up", "volume_off", "speed", "fullscreen", "fullscreen_exit", "zoom_in", "zoom_out", "fit_screen",
  "first_page", "last_page", "replay_10", "forward_10", "keyboard_arrow_left", "keyboard_arrow_right", "wrap_text", "format_list_numbered", "stop",
  // spaces
  "mail", "calendar_month", "contacts", "task_alt", "preview", "widgets", "brush", "palette",
  // paint
  "menu", "splitscreen_right", "splitscreen_bottom", "select", "lasso_select", "polyline", "select_all", "deselect", "content_cut", "aspect_ratio", "note_add", "keyboard", "arrow_selector_tool", "draw", "ink_highlighter", "ink_eraser", "horizontal_rule", "north_east", "rectangle", "circle",
  "title", "format_color_fill", "colorize", "crop", "undo", "redo", "pan_tool", "layers", "photo_library", "content_paste",
  "flip_to_front", "flip_to_back", "opacity", "line_weight",
  // agent / artifacts
  "smart_toy", "wand_stars", "lock", "lock_open", "verified_user", "gpp_maybe", "bug_report", "code_blocks", "deployed_code",
  "keyboard_double_arrow_left", "keyboard_double_arrow_right", "dock_to_left", "dock_to_right", "cloud_off", "wifi_off", "schedule",
];

// Glyphs Material Symbols lacks, drawn on the same 960 grid (viewBox 0 -960 960 960).
const CUSTOM = {
  // An artifact: a window with a code bracket and a spark, "something built".
  artifact: "M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h360v80H200v560h560v-360h80v360q0 33-23.5 56.5T760-120H200Zm160-160-120-120 120-120 42 42-78 78 78 78-42 42Zm240 0-42-42 78-78-78-78 42-42 120 120-120 120Zm120-340-25-55-55-25 55-25 25-55 25 55 55 25-55 25-25 55Z",
};

async function pathOf(name) {
  const svg = await readFile(join(source, `${name}.svg`), "utf8");
  const paths = [...svg.matchAll(/ d="([^"]+)"/g)].map((match) => match[1]);
  if (!paths.length) throw new Error(`No path in ${name}`);
  return paths.join(" ");
}

const icons = {};
for (const name of NAMES) {
  icons[name] = await pathOf(name);
  try { icons[`${name}.fill`] = await pathOf(`${name}-fill`); } catch { /* no filled variant */ }
}
Object.assign(icons, CUSTOM);

const addon = join(root, "thunderbird-addon");
await writeFile(join(addon, "shared/icons.js"), `// Generated by scripts/build-icons.mjs from Material Symbols Rounded (Apache-2.0). Do not edit.
export const ICONS = ${JSON.stringify(icons)};

/** An inline SVG icon; \`fill\` picks the filled variant when there is one. */
export function icon(name, { fill = false, size = 20, label } = {}) {
  const d = (fill && ICONS[\`\${name}.fill\`]) || ICONS[name];
  if (!d) throw new Error(\`Unknown icon \${name}\`);
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("viewBox", "0 -960 960 960");
  svg.setAttribute("width", size);
  svg.setAttribute("height", size);
  svg.setAttribute("class", "icon");
  if (label) svg.setAttribute("aria-label", label); else svg.setAttribute("aria-hidden", "true");
  const path = document.createElementNS("http://www.w3.org/2000/svg", "path");
  path.setAttribute("d", d);
  svg.append(path);
  return svg;
}
`);
await mkdir(join(addon, "icons"), { recursive: true });
for (const [name, d] of Object.entries(icons)) {
  await writeFile(join(addon, "icons", `${name}.svg`), `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960" fill="context-fill" fill-opacity="context-fill-opacity"><path d="${d}"/></svg>\n`);
}
console.log(`${Object.keys(icons).length} icons`);
